jenkins: don't mask the exit code on failed `git clone`
`git clone ... && cd ...` doesn't trigger `set -e` even if `git clone
...` exits with 1, leading to false positive test runs in certain cases:

```
Cloning into 'systemd-tmp'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
From https://github.com/systemd/systemd
 * [new ref]               refs/pull/23000/head -> pr
Previous HEAD position was 239adf0384 sd-ipv4acd: actually drop the arp packet from one of the host interface
Switched to branch 'pr'
fatal: Not a valid object name main
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Changes in this PR don't seem relevant, skipping...
```